### ISSUE TITLE
Unhandled 'error'

### ISSUE THREAD

**Issue by cflurin** [karbassi/netatmo#27]
Hi,

Is there a way to catch this error?

```sh
pi@rpi4:~/netatmo-test/node_modules/netatmo $ node test.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Authenticate error: invalid_grant
    at netatmo.handleRequestError (/home/pi/netatmo-test/node_modules/netatmo/netatmo.js:46:15)
    at .<anonymous> (/home/pi/netatmo-test/node_modules/netatmo/netatmo.js:115:19)
    at Request.self.callback (/home/pi/netatmo-test/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pi/netatmo-test/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/pi/netatmo-test/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:286:16)
```

test.js:
```javascript
var netatmo = require('./netatmo');

var auth = {
  "client_id": "my_client_id",
  "client_secret": "my_client_secret",
  "username": "my_username",
  "password": "my_password",
};

try {
  var api = new netatmo(auth);
} catch(err) {
  console.log("api error " + err.message);
}

// EXAMPLE #1

// Get Stations Data
// See docs: https://dev.netatmo.com/dev/resources/technical/reference/weatherstation/getstationsdata
try {
  api.getStationsData(function(err, devices) {
    console.log(devices);
  });
} catch(err) {
  console.log("getStationData error " + err.message);
}
```

**Comment by karbassi** [comment]
@cflurin Be sure to fill in the `var auth` variable.

**Comment by karbassi** [comment]
@cflurin I can't seem to replicate this, but based on [this comment](https://github.com/openhab/openhab1-addons/issues/3548#issuecomment-182859352), it may be that your have an invalid code, expired code, or missing args. 

> The Netatmo documentation states that the invalid_grant error is shown "In case of error (invalid code, expired code, missing args)"

Update the `test.js` auth variable and run `npm test` in this project root. What do you get? Can you paste me logs?

**Comment by cflurin** [comment]
@karbassi:
Thanks for your reply. 
Actually I'm using node-red-contrib-netatmo-dashboard that uses your netatmo.js, generally it works but sometimes it crashes.

Do you mean the `Catching Errors and Warnings` code? if yes, I reproduced the issue setting a wrong password, here is the logs:
```sh
Netatmo threw an error: Error: Authenticate error: invalid_grant
```

**Comment by cflurin** [comment]
... and this ist the log of test.js setting a wrong password:
```sh
pi@rpi4:~/netatmo-test/node_modules/netatmo $ node test
(node:8400) Warning: Possible EventEmitter memory leak detected. 11 authenticated listeners added. Use emitter.setMaxListeners() to increase limit
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Authenticate error: invalid_grant
    at netatmo.handleRequestError (/home/pi/netatmo-test/node_modules/netatmo/netatmo.js:46:15)
    at .<anonymous> (/home/pi/netatmo-test/node_modules/netatmo/netatmo.js:115:19)
    at Request.self.callback (/home/pi/netatmo-test/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pi/netatmo-test/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/pi/netatmo-test/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:286:16)
```

**Comment by cflurin** [comment]
I used you original test.js (to reproduce the error I've set a wrong password):
```sh
pi@rpi4:~/netatmo-test/node_modules/netatmo $ node test
(node:8459) Warning: Possible EventEmitter memory leak detected. 11 authenticated listeners added. Use emitter.setMaxListeners() to increase limit
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Authenticate error: invalid_grant
    at netatmo.handleRequestError (/home/pi/netatmo-test/node_modules/netatmo/netatmo.js:46:15)
    at .<anonymous> (/home/pi/netatmo-test/node_modules/netatmo/netatmo.js:115:19)
    at Request.self.callback (/home/pi/netatmo-test/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pi/netatmo-test/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/pi/netatmo-test/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:286:16)
```

**Comment by karbassi** [comment]
What happens when you use the right password?

**Comment by cflurin** [comment]
It works perfectly, but as I said above with node-red-contrib-netatmo-dashboard I request the data every 10 minutes, this works for a long time (days) until node-red crashes with:

```sh
Error: Authenticate error: invalid_grant
```

**Comment by cflurin** [comment]
... I've added this code:
```js
      api.on("error", function(error) {
        node.error('Netatmo threw an error: ' + error);
      });
```

to node-red-contrib-netatmo-dashboard on my test system. It seems to work.
